### ISSUE TITLE
Android crash 

### ISSUE THREAD

**Issue by Dawimpy** [rollerozxa-archive/rollertest#2]
When I'm trying to open this app. It just crash instantly...

Using latest APK (https://rollertest.voxelmanip.se/builds/rollertest_2022-11-05_332716983_android_arm64.apk)

**Comment by Dawimpy** [comment]
Looks like it's an upstream problem...

**Comment by rollerozxa** [comment]
Looks like it's a you problem... Too bad you didn't send any logcat logs so I could actually see what the issue is.

(The build works for me and for other people too, so can't reproduce)
