### ISSUE TITLE
ROllertest-only shading error

### ISSUE THREAD

**Issue by Unacceptium** [rollerozxa-archive/rollertest#4]
### Minetest version

```true
MT version 5.8DEV
2023.5.16
```

### Active renderer

OGLes 2

### Irrlicht device

ANDROID

### Operating system and version

Android 12 MagicUI 6

### Summary

rollertest crashes if i "sit" on a bike in the [bike] mod
or plaxing down the new blocks from Edit mod

### Steps to reproduce

download or join a server with the mod [bike]
"ride" a bike.
Or place down a new block from Edit mod.

**Comment by Unacceptium** [comment]
![Screenshot_20231022_200143](https://github.com/rollerozxa/rollertest/assets/145642963/462ea1e1-8b02-448e-bec0-c558701f4b53)

**Comment by Unacceptium** [comment]
the game crashes also when the new blocks from Edit mod get placed. this is kinda weird.
![Screenshot_20231111_084820](https://github.com/rollerozxa/rollertest/assets/145642963/ce797b1a-1868-4827-857d-cae7fd7cf374)

**Comment by rollerozxa** [comment]
This crash is caused with some certain models. It has been fixed in upstream with https://github.com/minetest/minetest/pull/13843, and I've pushed out a new version of ROllertest (2023.12.10) for review by Google Play which includes the fix. It should be available tomorrow.
